name: Release

on:
  push:
    tags:
      - 'v*'   # Trigger on version tags such as v1.0.0

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, macos-13, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cibuildwheel==2.*

      - name: Build wheels with cibuildwheel
        env:
          CIBW_TEST_COMMAND: python {package}/test_disjointset.py
        run: cibuildwheel --output-dir wheelhouse .

      - name: Upload built wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: wheelhouse/*.whl

  publish:
    # Wait for all platforms to build, then publish wheels and a source distribution.
    needs: build_wheels
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Download wheels (Ubuntu)
        uses: actions/download-artifact@v4
        with:
          name: wheels-ubuntu-latest
          path: wheels

      - name: Download wheels (macOS)
        uses: actions/download-artifact@v4
        with:
          name: wheels-macos-latest
          path: wheels

      - name: Download wheels (Windows)
        uses: actions/download-artifact@v4
        with:
          name: wheels-windows-latest
          path: wheels

      - name: Build source distribution
        run: |
          python -m pip install --upgrade pip setuptools wheel build pkginfo
          python -m build --sdist --outdir sdist

      - name: Copy to dist
        run: |
          mkdir dist
          cp wheels/* dist/
          cp sdist/* dist/
          ls dist/

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
